/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./../components/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./../components/ArrowRight.vue')['default']
    BaseButton: typeof import('./../components/BaseButton.vue')['default']
    BaseContainer: typeof import('./../components/BaseContainer.vue')['default']
    BaseGradientText: typeof import('./../components/BaseGradientText.vue')['default']
    BaseGridList: typeof import('./../components/BaseGridList.vue')['default']
    BaseHamburger: typeof import('./../components/BaseHamburger.vue')['default']
    BaseList: typeof import('./../components/BaseList.vue')['default']
    BaseLoader: typeof import('./../components/BaseLoader.vue')['default']
    BaseLogo: typeof import('./../components/BaseLogo.vue')['default']
    BaseProjectCard: typeof import('./../components/BaseProjectCard.vue')['default']
    BaseThemeToggle: typeof import('./../components/BaseThemeToggle.vue')['default']
    BaseWrapper: typeof import('./../components/BaseWrapper.vue')['default']
    IconArrowLeft: typeof import('./../components/IconArrowLeft.vue')['default']
    IconArrowRight: typeof import('./../components/IconArrowRight.vue')['default']
    IconCodeFill: typeof import('./../components/IconCodeFill.vue')['default']
    IconJS: typeof import('./../components/IconJS.vue')['default']
    IconPixiJS: typeof import('./../components/IconPixiJS.vue')['default']
    IconReact: typeof import('./../components/IconReact.vue')['default']
    IconTailwind: typeof import('./../components/IconTailwind.vue')['default']
    IconThreeJS: typeof import('./../components/IconThreeJS.vue')['default']
    IconVueJS: typeof import('./../components/IconVueJS.vue')['default']
    LogosPixijs: typeof import('./../components/LogosPixijs.vue')['default']
    MingcuteArrowLeftFill: typeof import('./../components/MingcuteArrowLeftFill.vue')['default']
    MingcuteArrowRightFill: typeof import('./../components/MingcuteArrowRightFill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillIconsThreejsLight: typeof import('./../components/SkillIconsThreejsLight.vue')['default']
    TheBanner: typeof import('./../components/TheBanner.vue')['default']
    TheBottom1: typeof import('./../components/TheBottom1.vue')['default']
    TheBottom2: typeof import('./../components/TheBottom2.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheHeader: typeof import('./../components/TheHeader.vue')['default']
    TheMain: typeof import('./../components/TheMain.vue')['default']
    TheMiddle1: typeof import('./../components/TheMiddle1.vue')['default']
    TheMiddle2: typeof import('./../components/TheMiddle2.vue')['default']
    TheNav: typeof import('./../components/TheNav.vue')['default']
    VscodeIconsFileTypeJsOfficial: typeof import('./../components/VscodeIconsFileTypeJsOfficial.vue')['default']
    VscodeIconsFileTypeReactjs: typeof import('./../components/VscodeIconsFileTypeReactjs.vue')['default']
    VscodeIconsFileTypeTailwind: typeof import('./../components/VscodeIconsFileTypeTailwind.vue')['default']
    VscodeIconsFileTypeVue: typeof import('./../components/VscodeIconsFileTypeVue.vue')['default']
  }
}
